### ISSUE TITLE
Add TikTok to Default Settings

### ISSUE THREAD

**Issue by cre8tivediva** [studiopress/simple-social-icons#114]
With the popularity of TikTok, we receive at least 5-7 support requests a day asking if TikTok can be added.

**Comment by restored316** [comment]
I agree!!  This should definitely be added!

**Comment by SusanRamsey** [comment]
This is a good idea!

**Comment by sandeejackson** [comment]
TikTok would be a great add, yes! It's definitely becoming more popular for businesses and nonprofits.

**Comment by restored316** [comment]
Also, remove Google + since it has been deprecated :)

**Comment by CarolynYalin** [comment]
Yes please, Tik Tok would be a great addition.

**Comment by emrdesignstudio** [comment]
Yes! adding Tik Tok and removing Google+ would be a great idea :)

**Comment by cre8tivediva** [comment]
There's an open item on Google + here - https://github.com/studiopress/simple-social-icons/issues/88.

**Comment by mjsdiaz** [comment]
I love the TikTok idea! And please, please remove Google+, so it will just disappear from all those sites that get a 404 error because the link no longer works. (I had to remove one from a site I just started working on)

**Comment by thaunak** [comment]
Suck a great idea since everyone is now on TikTok. :)

**Comment by mikezielonka** [comment]
It would be so rad to see a release with updated icons :)

**Comment by kienstra** [comment]
Added in https://github.com/studiopress/simple-social-icons/pull/119

**Comment by cre8tivediva** [comment]
Good morning, thank you so much for updating the plugin with all the new social media accounts. Could the list under the heading "**Which services are included?**" on the plugin page be updated to include the names of the new additions? Thanks in advance!

**Comment by cre8tivediva** [comment]
Also, a feature request on the plugin support page was - Patreon. This is a big one too. There are a lot of folks on Patreon now. TIA!

**Comment by kienstra** [comment]
Thanks, those are good ideas.

It's hard to say when the next release would be, though.
