### ISSUE TITLE
Obfuscate email addresses with antispambot()

### ISSUE THREAD

**Issue by nickcernis** [studiopress/simple-social-icons#14]
A user in the WP.org forums would like to see email addresses obfuscated with the [antispambot()](https://codex.wordpress.org/Function_Reference/antispambot) function that WP core provides.

https://wordpress.org/support/topic/ssi-does-not-allow-email-addresses-to-be-obfuscated?replies=3#post-7219162

I offered a workaround to use antispambot if the email is hard-coded, but it might be worth obfuscating email addresses by default.

**Comment by carasmo** [comment]
+1

**Comment by marksabbath** [comment]
Done by https://github.com/studiopress/simple-social-icons/pull/61

**Comment by dreamwhisper** [comment]
Confirmed if entered as plain email without mailto (https://github.com/studiopress/simple-social-icons/issues/73)
