### ISSUE TITLE
Update Author and Author URI to say StudioPress

### ISSUE THREAD

**Issue by jaygidwitz** [studiopress/simple-social-icons#53]
**plugin.php file**: update Author and Author URI to say StudioPress.

```
Author: StudioPress
Author URI: http://www.studiopress.com/
```

**Comment by marksabbath** [comment]
Fixed by #68.

**Comment by dreamwhisper** [comment]
@marksabbath Just double checking on the https for the URL. I am not seeing that was updated.

**Comment by dreamwhisper** [comment]
http://www.opensource.org/licenses/gpl-license.php can be changed to https. It redirects to https://www.opensource.org/licenses/gpl-license.php

**Comment by dreamwhisper** [comment]
@nickcernis @marksabbath I think this is the last extremely minor thing ^ of the existing 2.1 issues.

All other issues have been tested.

**Comment by nickcernis** [comment]
@dreamwhisper Thanks for your testing! https://github.com/studiopress/simple-social-icons/pull/86 looks good to merge now.

**Comment by marksabbath** [comment]
@dreamwhisper should be all fixed by https://github.com/studiopress/simple-social-icons/pull/86
