### ISSUE TITLE
Add filter to the markup output

### ISSUE THREAD

**Issue by lopwalj** [studiopress/simple-social-icons#59]
Hello.
I would love to see a filter in the `get_icon_markup` function output.
Actually, I want to add the attr `rel="nofollow"` to the links.

**Comment by dreamwhisper** [comment]
@marksabbath @nickcernis Is https://github.com/studiopress/simple-social-icons/pull/79 is ready to merge?

**Comment by nickcernis** [comment]
@dreamwhisper Yep! cc @marksabbath

**Comment by dreamwhisper** [comment]
Update to `return apply_filters( 'simple_social_icon_html', $markup, $icon, $label );` for easier control.

**Comment by nickcernis** [comment]
@dreamwhisper Nice catch! Added in https://github.com/studiopress/simple-social-icons/commit/4e519ed966c3b4521965b1301735cd3bf80b49e6.
