### ISSUE TITLE
Don't output inline CSS for inactive widgets

### ISSUE THREAD

**Issue by nickcernis** [studiopress/simple-social-icons#63]
CSS is currently output for widgets in the inactive section. Reproducible by:

1. Add a Simple Social Icon to any widget area, configure it, and save.
2. Move it to the inactive widgets area.
3. Search the front end source for `.simple-social-icons ul li a`. You'll see inline CSS on the page.

**Comment by dreamwhisper** [comment]
https://github.com/copyblogger/simple-social-icons/issues/8 is the original where this is mentioned.

**Comment by marksabbath** [comment]
This has been resolved by #60
