### ISSUE TITLE
SVG (and other URLs)

### ISSUE THREAD

**Issue by mattlawck** [studiopress/simple-social-icons#67]
This was submitted to Nathan direct:

On a site with HTTPS/SSL

A file with an insecure url of "http://www.acupuncture-answers.com/wp-content/plugins/simple-social-icons/symbol-defs.svg" was loaded via the javascript file: https://www.acupuncture-answers.com/wp-content/plugins/simple-social-icons/svgxuse.js?ver=1.1.21 on line 172. The insecure URL may not be directly contained in the script file and may exist elsewhere.

You may need to contact your web hosting provider for assistance.

This URL will need to be updated to use a secure URL for your padlock to return.

I would be happy to edit the images we're using for the SS plugin, however, the option to edit the icons/urls etc is now gone from our dashboard.

**Comment by nickcernis** [comment]
We could prompt them to check that the site's WordPress URL and Site URL start 'https://' and not 'http://' at Settings → General.

**Comment by mattlawck** [comment]
Confirm we aren't referencing as http

**Comment by marksabbath** [comment]
Simple Social Icon uses `plugin_dir_url` to look for URLs inside the WordPress, which automatically builds the scheme according to `is_ssl()` WordPress function. I've tested it on a regular WordPress install with and without SSL and both are working accordingly.
