### ISSUE TITLE
Missing rel="noopener" on links with target="_blank"

### ISSUE THREAD

**Issue by NormanHoehne** [studiopress/simple-social-icons#71]
Dear team,

you should add `rel="noopener"` for all links that open in a new window to improve security and performance.

Please take a look at:

- https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/
- https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/

Chrome has fixed this vulnerability long time a go, but e.g. firefox is still vulnerable.

Cheers,
Norman

**Comment by nickcernis** [comment]
To test (feature/noopener branch):

- Check “Open links in new window?” in widget settings:

Confirm:

- [ ] Icon anchor elements contain `rel="noopener noreferrer"` as well as `target="_blank"`, and open in new window.

**Comment by dreamwhisper** [comment]
@nickcernis ready to merge!

**Comment by nickcernis** [comment]
@dreamwhisper Merged in https://github.com/studiopress/simple-social-icons/pull/85. Thanks for looking at this!
