### ISSUE TITLE
Equal identifiers when widget is used multiple times on one page

### ISSUE THREAD

**Issue by NormanHoehne** [studiopress/simple-social-icons#72]
If one page carries two simple social icon widgets with the same social media icon, e.g.:

1. Facebook Icon in the Navigation Bar
2. Facebook Icon in the Footer Section

The page will have four elements with the same id:

- 2x the same title id
- 2x the same svg id

**Comment by dreamwhisper** [comment]
This should be resolved in the develop branch for next release.

**Comment by NormanHoehne** [comment]
✔️ The mentioned issue "2x the same title id" is now resolved with version 3.0.0
❌ The mentioned issue "2x the same svg id" still remains on version 3.0.0 - I'm not sure if this is valid Markup, can someone double check that?

**Comment by nickcernis** [comment]
Thanks for testing this, @NormanHoehne!

I see the same duplicate ID reused in the SVG markup itself, but it doesn't generate any validation errors for me. The way it's loaded via the `<use>` element effectively places it in a separate DOM tree:

> The effect is the same as if the nodes were deeply cloned into a non-exposed DOM… 
>  — https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use

Chrome represents this as descending from the shadow-root:

![screen shot on 2018-10-11 at 12 39 12](https://user-images.githubusercontent.com/647669/46798621-c3282300-cd52-11e8-80c7-9fd88bf5fd96.png)

So I expect that particular duplicated ID to be safe to ignore here.

**Comment by NormanHoehne** [comment]
Thank you for the clarification @nickcernis, I can live with that!  :) 👍
