### ISSUE TITLE
multiple instances on single page

### ISSUE THREAD

**Issue by ctalkington** [studiopress/simple-social-icons#8]
the style selector used causes issues on pages with multiple instances.

would suggest selector that uses widget id. will open PR if come up with solution.

**Comment by dreamwhisper** [comment]
Debatable whether this should have a separate issue, but inactive widgets also cause a problem. CSS output comes from the last widget added regardless of whether the widget is active. 

Many people don't think to look in the inactive widgets area when trying to determine why their settings aren't updating the front end.

**Comment by ctalkington** [comment]
semi related is #12 which causes php notice when no widgets are setup.

**Comment by carasmo** [comment]
+1

**Comment by carasmo** [comment]
+1 -- It's not logical for most users to see the ability to style the icons and then have their header icons (in a light background, for example), take on the style of the footer icons which went on a dark background.

**Comment by carasmo** [comment]
https://github.com/copyblogger/simple-social-icons/pull/60

**Comment by marksabbath** [comment]
Fixed by #60
