### ISSUE TITLE
Multiple instances of the widget on the same page breaks styling

### ISSUE THREAD

**Issue by JiveDig** [studiopress/simple-social-icons#81]
Many users in the Genesis Slack have expressed similar frustration when using multiple instances of SSI on the same page. This happens quite often, sidebar and header or footer for example. I actually thought there was an open issue here, but I'm not seeing it.

All of the style settings (size, colors, border, border-radius, alignment) need to target the specific instance.

Many of us have since started using and recommending another plugin (https://wordpress.org/plugins/lightweight-social-icons/) but I'd love to keep it all with StudioPress plugins, especially for Mai Theme demos.

FWIW, may be related to https://github.com/studiopress/simple-social-icons/issues/72

**Comment by nickcernis** [comment]
@JiveDig This should be solved in https://github.com/studiopress/simple-social-icons/pull/60 (part of the next release). Please feel free to test and comment, though!

**Comment by JiveDig** [comment]
🤘
