### ISSUE TITLE
Fix AMP validation error for svgxuse.js

### ISSUE THREAD

**Issue by nickcernis** [studiopress/simple-social-icons#96]
Bare `script` elements are not allowed by AMP, so our use of `svgxuse.js` results in a validation error on all sites using the plugin with AMP.

https://github.com/studiopress/simple-social-icons/blob/a9105323026d27b249b780ede7f79e4ca0c85da5/simple-social-icons.php#L487

<img width="1015" alt="Screenshot 2019-05-01 at 12 13 36" src="https://user-images.githubusercontent.com/647669/57013177-93ffd300-6c0a-11e9-81f7-a89addc7f0ee.png">

Options to solve this include:

1. Remove svgxuse.js altogether. (IE 9, 10, 11 would fail to show social icons on both the non-AMP and AMP version of sites.)
2. Load svgxuse.js only if AMP is not in use. (IE 9, 10, 11 would fail to show social icons on the AMP version of the site.)

Option two might be best for now given that IE 11 is still in the browser support list for many StudioPress themes, such as Genesis Sample, and IE 11 is not officially supported by AMP anyway: https://amp.dev/support/faq/supported-browsers

```diff
+if ( function_exists( 'genesis_is_amp' ) && ! genesis_is_amp() ) {
	wp_enqueue_script('svg-x-use', plugin_dir_url(__FILE__) . 'svgxuse.js', array(), '1.1.21' );
+}
```

**Comment by dreamwhisper** [comment]
@nickcernis I think option 2 is good. I've already tested that solution too :)

**Comment by dreamwhisper** [comment]
svgxuse.js was removed previously
